//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICompare.Setup.SchedulerPostInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICompare.Setup.SchedulerPostInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Master&quot; connectionString=&quot;[MASTERCONNECTIONSTRING]&quot;/&gt;
        ///  &lt;/connectionStrings&gt;
        ///
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;SchedulerName&quot; value=&quot;FluidScheduler&quot;/&gt;
        ///    &lt;add key=&quot;ProcessPath&quot; value=&quot;&quot; /&gt;
        ///    &lt;add key=&quot;HealthTimeout&quot; value=&quot;120&quot; /&gt;
        ///    &lt;add key=&quot;RunnerId&quot; value=&quot;&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Master&quot; connectionString=&quot;[MASTERCONNECTIONSTRING]&quot;/&gt;
        ///  &lt;/connectionStrings&gt;
        ///
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;RunnerId&quot; value=&quot;&quot; /&gt;
        ///
        ///    &lt;!-- Message Logger --&gt;
        ///    &lt;add key=&quot;LogPresenterTypes&quot; value=&quot;SqlLogPresenter&quot; /&gt;
        ///    &lt;add key=&quot;CanLogExceptionDetail&quot; value=&quot;True&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fluid_Business_SchedulerService_exe {
            get {
                return ResourceManager.GetString("Fluid_Business_SchedulerService_exe", resourceCulture);
            }
        }
    }
}
