//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICompare.Setup.ServicesPostInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICompare.Setup.ServicesPostInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;probing privatePath=&quot;lib;lib/icompare;lib/devexpress;lib/fluid;lib/fusion&quot; /&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///  
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Operations&quot; connectionString=&quot;{CONNECTIONSTRING}&quot; /&gt;
        ///  &lt;/connectionStri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICompare_Business_AllocationService_exe {
            get {
                return ResourceManager.GetString("ICompare_Business_AllocationService_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;probing privatePath=&quot;lib;lib/icompare;lib/devexpress;lib/fluid;lib/fusion&quot; /&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///  
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Operations&quot; connectionString=&quot;{CONNECTIONSTRING}&quot;/&gt;
        ///  &lt;/connectionStrings&gt;
        ///
        ///  &lt;appSetti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICompare_Business_MatchingService_exe {
            get {
                return ResourceManager.GetString("ICompare_Business_MatchingService_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;probing privatePath=&quot;lib;lib/icompare;lib/devexpress;lib/fluid;lib/fusion&quot; /&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///  
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Operations&quot; connectionString=&quot;{CONNECTIONSTRING}&quot;/&gt;
        ///  &lt;/connectionStrings&gt;
        ///
        ///  &lt;appSetti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICompare_Business_ValidationService_exe {
            get {
                return ResourceManager.GetString("ICompare_Business_ValidationService_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;probing privatePath=&quot;lib;lib/icompare;lib/devexpress;lib/fluid;lib/fusion&quot; /&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Operations&quot; connectionString=&quot;{CONNECTIONSTRING}&quot; /&gt;
        ///  &lt;/connectionString [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICompare_Test_AllocationEngineConsole_exe {
            get {
                return ResourceManager.GetString("ICompare_Test_AllocationEngineConsole_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;probing privatePath=&quot;lib;lib/icompare;lib/devexpress;lib/fluid;lib/fusion&quot; /&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Operations&quot; connectionString=&quot;{CONNECTIONSTRING}&quot;/&gt;
        ///  &lt;/connectionStrings&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICompare_Test_MatchingEngineConsole_exe {
            get {
                return ResourceManager.GetString("ICompare_Test_MatchingEngineConsole_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///&lt;!--This is validation console--&gt;
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;probing privatePath=&quot;lib;lib/icompare;lib/devexpress;lib/fluid;lib/fusion&quot; /&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///  
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Operations&quot; connectionString=&quot;{CONNECTIONSTRING}&quot;/&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ICompare_Test_ValidationEngineConsole_exe {
            get {
                return ResourceManager.GetString("ICompare_Test_ValidationEngineConsole_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;probing privatePath=&quot;lib;lib/icompare;lib/devexpress;lib/fluid;lib/fusion&quot; /&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///  
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;Operations&quot; connectionString=&quot;{CONNECTIONSTRING}&quot;/&gt;
        ///  &lt;/connectionStrings&gt;
        ///
        ///  &lt;appSetti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportConfig {
            get {
                return ResourceManager.GetString("ImportConfig", resourceCulture);
            }
        }
    }
}
